//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Addons.PushAndMerge.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PushAndMergeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PushAndMergeResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Addons.PushAndMerge.Properties.PushAndMergeResources", typeof(PushAndMergeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [EN]2. Alle anderen Titel ähnelt.
        /// </summary>
        internal static string allOtherTitlesSubtitleLabel {
            get {
                return ResourceManager.GetString("allOtherTitlesSubtitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        internal static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Items cannot be copied within the same project. ähnelt.
        /// </summary>
        internal static string CantMoveItemsInTheSameProject {
            get {
                return ResourceManager.GetString("CantMoveItemsInTheSameProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [EN]Kopieren, bei bei gleichem Ersteller und Erstellungsdatum duplizieren ähnelt.
        /// </summary>
        internal static string CloneKnowledgeItemOnMatchText {
            get {
                return ResourceManager.GetString("CloneKnowledgeItemOnMatchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [EN]In das Zielprojekt kopieren ähnelt.
        /// </summary>
        internal static string copyOtherTitlesCheckboxText {
            get {
                return ResourceManager.GetString("copyOtherTitlesCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom fields ähnelt.
        /// </summary>
        internal static string CustomFields {
            get {
                return ResourceManager.GetString("CustomFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finish ähnelt.
        /// </summary>
        internal static string FinishButton {
            get {
                return ResourceManager.GetString("FinishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1031{\fonttbl{\f0\fnil\fcharset0 Calibri;}{\f1\fnil\fcharset2 Symbol;}}
        ///{\*\generator Riched20 10.0.16299}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\b\f0\fs22\lang7 Alle anderen Titel\b0\par
        ///Alle anderen Titel umfassen solche Titel, f\&apos;fcr die im Zielprojekt\par
        ///
        ///\pard{\pntext\f1\&apos;B7\tab}{\*\pn\pnlvlblt\pnf1\pnindent0{\pntxtb\&apos;B7}}\fi-360\li720\sa200\sl276\slmult1 kein Titel mit gleicher ID\par
        ///{\pntext\f1\&apos;B7\tab}kein Titel mit 100% \&apos;dcbereinstimmung\pa [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string HelpText_AllOtherTitles {
            get {
                return ResourceManager.GetString("HelpText_AllOtherTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1031{\fonttbl{\f0\fnil\fcharset0 Calibri;}{\f1\fnil\fcharset2 Symbol;}}
        ///{\*\generator Riched20 10.0.16299}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang7 Titel mit einer 100%-\&apos;dcbereinstimmung in wesentlichen Feldern\par
        ///Die Bedingung tritt ein, wenn die Inhalte in allen folgenden Feldern bei dem Titel im Ausgangsprojekt und dem Titel im Zielprojekt identisch sind:\par
        ///
        ///\pard{\pntext\f1\&apos;B7\tab}{\*\pn\pnlvlblt\pnf1\pnindent0{\pntxtb\&apos;B7}}\fi-358\ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string HelpText_MergeTitlesWithEqualEssentialFields {
            get {
                return ResourceManager.GetString("HelpText_MergeTitlesWithEqualEssentialFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1031{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.16299}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang7 Titel mit gleicher StaticID\par
        ///Wenn ein Titel von einem Quell- in ein Zielprojekt kopiert wird, erh\&apos;e4lt er eine neue interne ID.\par
        ///Die ehemalige ID im Quellprojekt wird zudem im internen Feld \i StaticID\i0  festgehalten. Auf diese Weise kann Citavi feststellen, welcher Titel in Quell- und Zielprojekt zusammengeh\&apos;f6ren [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string HelpText_MergeTitlesWithEqualStaticId {
            get {
                return ResourceManager.GetString("HelpText_MergeTitlesWithEqualStaticId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1031{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.16299}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang7 Titel mit gleicher ID\par
        ///Es werden lediglich die ID der Titel miteinander verglichen. Die Bedingung tritt bei Titeln mit mehreren IDs ein, wenn mindestens eine ID die gleiche ist.\par
        ///} ähnelt.
        /// </summary>
        internal static string HelpText_MergeTitlesWithSameId {
            get {
                return ResourceManager.GetString("HelpText_MergeTitlesWithSameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1031{\fonttbl{\f0\fnil\fcharset0 Calibri;}{\f1\fnil\fcharset2 Symbol;}}
        ///{\*\generator Riched20 10.0.16299}\viewkind4\uc1 
        ///\pard\sl276\slmult1\f0\fs22\lang7 Daten f\&apos;fcr zu kopierende Titel\par
        ///\par
        ///Ihre Auswahl enth\&apos;e4lt Titel, die in das Zielprojekt kopiert werden sollen.\par
        ///\par
        ///Diese Daten werden in jedem Falle mit den Titeln kopiert:\par
        ///\par
        ///
        ///\pard{\pntext\f1\&apos;B7\tab}{\*\pn\pnlvlblt\pnf1\pnindent0{\pntxtb\&apos;B7}}\fi-360\li720\sl276\slmult1 Wissen [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string HelpText_SelectDataToCopy {
            get {
                return ResourceManager.GetString("HelpText_SelectDataToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [EN]Kopieren, bei gleichem Ersteller und Erstellungsdatum ignorieren ähnelt.
        /// </summary>
        internal static string IgnoreKnowledgeItemOnMatchText {
            get {
                return ResourceManager.GetString("IgnoreKnowledgeItemOnMatchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ignore ähnelt.
        /// </summary>
        internal static string ignoreOtherTitlesCheckboxText {
            get {
                return ResourceManager.GetString("ignoreOtherTitlesCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knowledgeitems ähnelt.
        /// </summary>
        internal static string KnowledgeItemsLabel {
            get {
                return ResourceManager.GetString("KnowledgeItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [EN]Titel mit einer 100%-Übereinstimmung in wesentlichen Feldern ähnelt.
        /// </summary>
        internal static string mergeEssentialFieldsCheckboxText {
            get {
                return ResourceManager.GetString("mergeEssentialFieldsCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Complete all ähnelt.
        /// </summary>
        internal static string MergeReferenceOptionComplete {
            get {
                return ResourceManager.GetString("MergeReferenceOptionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Complete if empty ähnelt.
        /// </summary>
        internal static string MergeReferenceOptionCompleteIfEmpty {
            get {
                return ResourceManager.GetString("MergeReferenceOptionCompleteIfEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ignore ähnelt.
        /// </summary>
        internal static string MergeReferenceOptionIgnore {
            get {
                return ResourceManager.GetString("MergeReferenceOptionIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Override ähnelt.
        /// </summary>
        internal static string MergeReferenceOptionOverride {
            get {
                return ResourceManager.GetString("MergeReferenceOptionOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [EN]Titel mit gleicher ID (ISBN, DOI, PubMedID, PMC, arXiv) ähnelt.
        /// </summary>
        internal static string mergeSameIdCheckboxText {
            get {
                return ResourceManager.GetString("mergeSameIdCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [EN]Titel mit gleicher StaticID ähnelt.
        /// </summary>
        internal static string mergeStaticIdCheckboxText {
            get {
                return ResourceManager.GetString("mergeStaticIdCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New project ... ähnelt.
        /// </summary>
        internal static string NewProjectButtonText {
            get {
                return ResourceManager.GetString("NewProjectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        internal static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open project ... ähnelt.
        /// </summary>
        internal static string OpenProjectButtonText {
            get {
                return ResourceManager.GetString("OpenProjectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projectname ähnelt.
        /// </summary>
        internal static string ProjectNameLabel {
            get {
                return ResourceManager.GetString("ProjectNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [EN]Wissenselemente in ein Citavi-Projekt kopieren ähnelt.
        /// </summary>
        internal static string PushAndMergeCommandButtonText {
            get {
                return ResourceManager.GetString("PushAndMergeCommandButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0:The reference|All {0} references} in this project ähnelt.
        /// </summary>
        internal static string ReferenceSelectionAll_Smart {
            get {
                return ResourceManager.GetString("ReferenceSelectionAll_Smart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The {0:reference|{0} references} in the current selection ähnelt.
        /// </summary>
        internal static string ReferenceSelectionFiltered_Smart {
            get {
                return ResourceManager.GetString("ReferenceSelectionFiltered_Smart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0:The selected reference|The {0} selected references} ähnelt.
        /// </summary>
        internal static string ReferenceSelectionSelected_Smart {
            get {
                return ResourceManager.GetString("ReferenceSelectionSelected_Smart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [EN]1. Titel, deren Daten im Zielprojekt zusammengeführt werden ähnelt.
        /// </summary>
        internal static string TitleSelectionMergeSubtitleLabel {
            get {
                return ResourceManager.GetString("TitleSelectionMergeSubtitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [EN]Einschränkungen / Einstellungen ähnelt.
        /// </summary>
        internal static string TitleSelectionTabSettingsLabel {
            get {
                return ResourceManager.GetString("TitleSelectionTabSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [EN]Titel auswählen ähnelt.
        /// </summary>
        internal static string TitleSelectionTabTitle {
            get {
                return ResourceManager.GetString("TitleSelectionTabTitle", resourceCulture);
            }
        }
    }
}
