//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Addons.BookOrderByEmail.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BookOrderByEmailResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BookOrderByEmailResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Addons.BookOrderByEmail.Properties.BookOrderByEmailResources", typeof(BookOrderByEmailResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addon {
            get {
                object obj = ResourceManager.GetObject("addon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ConfigDialog_Cancel {
            get {
                return ResourceManager.GetString("ConfigDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order text.
        /// </summary>
        internal static string ConfigDialog_lbl_Body {
            get {
                return ResourceManager.GetString("ConfigDialog_lbl_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient (Outlook).
        /// </summary>
        internal static string ConfigDialog_lbl_Receiver {
            get {
                return ResourceManager.GetString("ConfigDialog_lbl_Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ConfigDialog_Ok {
            get {
                return ResourceManager.GetString("ConfigDialog_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure ordering.
        /// </summary>
        internal static string ConfigDialog_Text {
            get {
                return ResourceManager.GetString("ConfigDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure ordering….
        /// </summary>
        internal static string ConfigureOrders {
            get {
                return ResourceManager.GetString("ConfigureOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by email (Clipboard)….
        /// </summary>
        internal static string OrderByClipboard {
            get {
                return ResourceManager.GetString("OrderByClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by email (Outlook)….
        /// </summary>
        internal static string OrderByEMail {
            get {
                return ResourceManager.GetString("OrderByEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}
        ///
        ///
        ///----------------------------------------------------
        ///
        ///{0}
        ///ISBN: {1}
        ///
        ///----------------------------------------------------
        ///This email was generated automatically with:
        ///Citavi – Reference Management and Knowledge Organization 
        ///http://www.citavi.com.
        /// </summary>
        internal static string OrderByEMailBodyText {
            get {
                return ResourceManager.GetString("OrderByEMailBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;missing&gt;.
        /// </summary>
        internal static string OrderByEMailBodyTextISBNMissing {
            get {
                return ResourceManager.GetString("OrderByEMailBodyTextISBNMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to Outlook.
        ///
        ///Please check if Citavi and Outlook are being run with the same rights..
        /// </summary>
        internal static string OutlookRightsMessage {
            get {
                return ResourceManager.GetString("OutlookRightsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string TasksOrder {
            get {
                return ResourceManager.GetString("TasksOrder", resourceCulture);
            }
        }
    }
}
