//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Addons.ImportSequenceNumber.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImportSequenceNumberResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImportSequenceNumberResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Addons.ImportSequenceNumber.Properties.ImportSequenceNumberResource" +
                            "s", typeof(ImportSequenceNumberResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which field do you want to import the sequence numbers into?.
        /// </summary>
        internal static string ChooseFieldMessage {
            get {
                return ResourceManager.GetString("ChooseFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sequence numbers were imported successfully..
        /// </summary>
        internal static string CompleteMultipleResultsMessage {
            get {
                return ResourceManager.GetString("CompleteMultipleResultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One sequence number was imported successfully..
        /// </summary>
        internal static string CompleteSingleResultMessage {
            get {
                return ResourceManager.GetString("CompleteSingleResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sequence numbers were imported..
        /// </summary>
        internal static string CompleteZeroResultMessage {
            get {
                return ResourceManager.GetString("CompleteZeroResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected project is not compatible with this project. Select the Citavi project that was converted to this Citavi 6 project..
        /// </summary>
        internal static string FoundReferenceCountNull {
            get {
                return ResourceManager.GetString("FoundReferenceCountNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import sequence numbers….
        /// </summary>
        internal static string MenuCaption {
            get {
                return ResourceManager.GetString("MenuCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s only possible to import sequence numbers from local projects..
        /// </summary>
        internal static string OnlyDesktopProjectsSupport {
            get {
                return ResourceManager.GetString("OnlyDesktopProjectsSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citavi projects|*.ctv5;*.ctv4;*.ctt4;*.ctv3;*.ctt3.
        /// </summary>
        internal static string OpenFileDialogFilters {
            get {
                return ResourceManager.GetString("OpenFileDialogFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Citavi Project.
        /// </summary>
        internal static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid Citavi project..
        /// </summary>
        internal static string OpenProjectConfigurationException {
            get {
                return ResourceManager.GetString("OpenProjectConfigurationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password-protected Citavi projects are not supported..
        /// </summary>
        internal static string OpenProtectedProjectMessage {
            get {
                return ResourceManager.GetString("OpenProtectedProjectMessage", resourceCulture);
            }
        }
    }
}
