//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Addons.ReferenceGridFormWorkSpaceEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReferenceGridFormWorkSpaceEditorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReferenceGridFormWorkSpaceEditorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Addons.ReferenceGridFormWorkSpaceEditor.Properties.ReferenceGridFor" +
                            "mWorkSpaceEditorResources", typeof(ReferenceGridFormWorkSpaceEditorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save new work area....
        /// </summary>
        internal static string Button_CreateWorkSpace {
            get {
                return ResourceManager.GetString("Button_CreateWorkSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage work areas....
        /// </summary>
        internal static string Button_EditWorkSpaces {
            get {
                return ResourceManager.GetString("Button_EditWorkSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work areas.
        /// </summary>
        internal static string Menu_Caption {
            get {
                return ResourceManager.GetString("Menu_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string NameEditor_Button_Cancel {
            get {
                return ResourceManager.GetString("NameEditor_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string NameEditor_Button_Create {
            get {
                return ResourceManager.GetString("NameEditor_Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string NameEditor_Button_Rename {
            get {
                return ResourceManager.GetString("NameEditor_Button_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work area name.
        /// </summary>
        internal static string NameEditor_Form_Text {
            get {
                return ResourceManager.GetString("NameEditor_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work area name:.
        /// </summary>
        internal static string NameEditor_Label_Name {
            get {
                return ResourceManager.GetString("NameEditor_Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap remove {
            get {
                object obj = ResourceManager.GetObject("remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up {
            get {
                object obj = ResourceManager.GetObject("up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string WorkSpaceEditor_Button_Close {
            get {
                return ResourceManager.GetString("WorkSpaceEditor_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save new work area....
        /// </summary>
        internal static string WorkSpaceEditor_Button_ToolTip_Add {
            get {
                return ResourceManager.GetString("WorkSpaceEditor_Button_ToolTip_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete work area.
        /// </summary>
        internal static string WorkSpaceEditor_Button_ToolTip_Remove {
            get {
                return ResourceManager.GetString("WorkSpaceEditor_Button_ToolTip_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage work areas.
        /// </summary>
        internal static string WorkSpaceEditor_Form_Text {
            get {
                return ResourceManager.GetString("WorkSpaceEditor_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete &quot;{0}&quot;?.
        /// </summary>
        internal static string WorkSpaceEditor_Messages_RemoveWorkSpace {
            get {
                return ResourceManager.GetString("WorkSpaceEditor_Messages_RemoveWorkSpace", resourceCulture);
            }
        }
    }
}
