//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Addons.ReferenceKnowledgeItemsMatchingAddon.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Addons.ReferenceKnowledgeItemsMatchingAddon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addon {
            get {
                object obj = ResourceManager.GetObject("addon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Match properties automatically ähnelt.
        /// </summary>
        internal static string CommandbarButton {
            get {
                return ResourceManager.GetString("CommandbarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die www.citavi.com/ReferenceKnowledgeItemsMatchingAddon ähnelt.
        /// </summary>
        internal static string Help_Url {
            get {
                return ResourceManager.GetString("Help_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [en] Soll der Abgleich gemäß den gewählten Einstellungen für bereits vorhandene Elemente durchgeführt werden? ähnelt.
        /// </summary>
        internal static string MessageBox_MatchingForExistingItems {
            get {
                return ResourceManager.GetString("MessageBox_MatchingForExistingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [en] Abgleiche aktivieren ähnelt.
        /// </summary>
        internal static string SettingsDialog_ActivateMatching {
            get {
                return ResourceManager.GetString("SettingsDialog_ActivateMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string SettingsDialog_Cancel {
            get {
                return ResourceManager.GetString("SettingsDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Categeories ähnelt.
        /// </summary>
        internal static string SettingsDialog_Categories {
            get {
                return ResourceManager.GetString("SettingsDialog_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [en] Welche Elemente sollen automatisch vom Wissenselementen auf ihren Titel abgeglichen werden? ähnelt.
        /// </summary>
        internal static string SettingsDialog_DescriptionFromKnowdlegeItemToReference {
            get {
                return ResourceManager.GetString("SettingsDialog_DescriptionFromKnowdlegeItemToReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [en] Welche Elemente sollen automatisch vom Titel auf seine Wissenselemente abgeglichen werden? ähnelt.
        /// </summary>
        internal static string SettingsDialog_DescriptionFromReferenceToKnowledgeItems {
            get {
                return ResourceManager.GetString("SettingsDialog_DescriptionFromReferenceToKnowledgeItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Groups ähnelt.
        /// </summary>
        internal static string SettingsDialog_Groups {
            get {
                return ResourceManager.GetString("SettingsDialog_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        internal static string SettingsDialog_Help {
            get {
                return ResourceManager.GetString("SettingsDialog_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keywords ähnelt.
        /// </summary>
        internal static string SettingsDialog_Keywords {
            get {
                return ResourceManager.GetString("SettingsDialog_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keywords (not recommended) ähnelt.
        /// </summary>
        internal static string SettingsDialog_Keywords_NotRecommended {
            get {
                return ResourceManager.GetString("SettingsDialog_Keywords_NotRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string SettingsDialog_Ok {
            get {
                return ResourceManager.GetString("SettingsDialog_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [en] Abgleich zwischen Titel und Wissenselementen ähnelt.
        /// </summary>
        internal static string SettingsDialog_Text {
            get {
                return ResourceManager.GetString("SettingsDialog_Text", resourceCulture);
            }
        }
    }
}
