//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Addons.ReferenceEvaluation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReferenceEvaluationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReferenceEvaluationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Addons.ReferenceEvaluation.Properties.ReferenceEvaluationResources", typeof(ReferenceEvaluationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addon {
            get {
                object obj = ResourceManager.GetObject("addon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Counts.
        /// </summary>
        internal static string Addon_Command {
            get {
                return ResourceManager.GetString("Addon_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of references by category.
        /// </summary>
        internal static string CategoryEvaluator_Caption {
            get {
                return ResourceManager.GetString("CategoryEvaluator_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No categories were found..
        /// </summary>
        internal static string CategoryEvaluator_NoCategories {
            get {
                return ResourceManager.GetString("CategoryEvaluator_NoCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number by project.
        /// </summary>
        internal static string Evaluation_CountByProject {
            get {
                return ResourceManager.GetString("Evaluation_CountByProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number by selection.
        /// </summary>
        internal static string Evaluation_CountBySelection {
            get {
                return ResourceManager.GetString("Evaluation_CountBySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Evaluator_Count {
            get {
                return ResourceManager.GetString("Evaluator_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Evaluator_Name {
            get {
                return ResourceManager.GetString("Evaluator_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Evaluator_Sex {
            get {
                return ResourceManager.GetString("Evaluator_Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        internal static string Form_Choice {
            get {
                return ResourceManager.GetString("Form_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        internal static string Form_Clipboard {
            get {
                return ResourceManager.GetString("Form_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Form_Close {
            get {
                return ResourceManager.GetString("Form_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Form_Options {
            get {
                return ResourceManager.GetString("Form_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Form_Result {
            get {
                return ResourceManager.GetString("Form_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show header.
        /// </summary>
        internal static string Form_ShowHeader {
            get {
                return ResourceManager.GetString("Form_ShowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts.
        /// </summary>
        internal static string Form_Text {
            get {
                return ResourceManager.GetString("Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of references by keyword.
        /// </summary>
        internal static string KeywordsEvaluator_Caption {
            get {
                return ResourceManager.GetString("KeywordsEvaluator_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No keywords were found..
        /// </summary>
        internal static string KeywordsEvaluator_NoKeywords {
            get {
                return ResourceManager.GetString("KeywordsEvaluator_NoKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of references by author and gender.
        /// </summary>
        internal static string PersonAndSexEvaluator_Caption {
            get {
                return ResourceManager.GetString("PersonAndSexEvaluator_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of references by person.
        /// </summary>
        internal static string PersonEvaluator_Caption {
            get {
                return ResourceManager.GetString("PersonEvaluator_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No persons were found..
        /// </summary>
        internal static string PersonEvaluator_NoPersons {
            get {
                return ResourceManager.GetString("PersonEvaluator_NoPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of links to other references for each reference.
        /// </summary>
        internal static string TwoLinksEvaluator_Caption {
            get {
                return ResourceManager.GetString("TwoLinksEvaluator_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string TwoLinksEvaluator_From {
            get {
                return ResourceManager.GetString("TwoLinksEvaluator_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No references were selected..
        /// </summary>
        internal static string TwoLinksEvaluator_NoReferences {
            get {
                return ResourceManager.GetString("TwoLinksEvaluator_NoReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short title.
        /// </summary>
        internal static string TwoLinksEvaluator_ShortTitle {
            get {
                return ResourceManager.GetString("TwoLinksEvaluator_ShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string TwoLinksEvaluator_To {
            get {
                return ResourceManager.GetString("TwoLinksEvaluator_To", resourceCulture);
            }
        }
    }
}
