//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Addons.CheckUrlAndSetDate.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CheckUrlAndSetDateResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CheckUrlAndSetDateResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Addons.CheckUrlAndSetDate.Properties.CheckUrlAndSetDateResources", typeof(CheckUrlAndSetDateResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addon {
            get {
                object obj = ResourceManager.GetObject("addon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check links in the online address field.
        /// </summary>
        internal static string CheckUrlAndSetDateCommandText {
            get {
                return ResourceManager.GetString("CheckUrlAndSetDateCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  *** link {0} checked on {1}: {2}; original access date: {3} ***.
        /// </summary>
        internal static string LinkCheckNotes {
            get {
                return ResourceManager.GetString("LinkCheckNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} links checked:
        ///{1} URLs valid
        ///{2} URLs not reachable
        ///Would you like to show a selection of references with an unreachable online address?.
        /// </summary>
        internal static string MacroResultMessage {
            get {
                return ResourceManager.GetString("MacroResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No references were found with links in the online address field..
        /// </summary>
        internal static string NoReferencesFoundedMessage {
            get {
                return ResourceManager.GetString("NoReferencesFoundedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References with invalid URLs.
        /// </summary>
        internal static string ReferenceInvalidFilterName {
            get {
                return ResourceManager.GetString("ReferenceInvalidFilterName", resourceCulture);
            }
        }
    }
}
