//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Addons.SendReferenceByEmail.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SendReferenceByEmailResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SendReferenceByEmailResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Addons.SendReferenceByEmail.Properties.SendReferenceByEmailResource" +
                            "s", typeof(SendReferenceByEmailResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addon {
            get {
                object obj = ResourceManager.GetObject("addon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send reference by email.
        /// </summary>
        internal static string ButtonCaption {
            get {
                return ResourceManager.GetString("ButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to Outlook.
        ///
        ///Please check if Citavi and Outlook are being run with the same rights..
        /// </summary>
        internal static string OutlookRightsMessage {
            get {
                return ResourceManager.GetString("OutlookRightsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, 
        ///
        ///I thought you might like this reference from the Citavi project &quot;{0}&quot;:
        ///{1}
        ///
        ///Hint:
        ///The attached RIS file contains the bibliographic information for the reference above. You can import this file into Citavi (see www.citavi.com/ris) or another reference management program..
        /// </summary>
        internal static string SendReferenceByEMailBodyText {
            get {
                return ResourceManager.GetString("SendReferenceByEMailBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, 
        ///
        ///I thought you might like this reference from the Citavi project &quot;{0}&quot;:
        ///{1}
        ///
        ///Attachments:
        ///{2}
        ///
        ///Hint:
        ///The attached RIS file contains the bibliographic information for the reference above. You can import this file into Citavi (see www.citavi.com/ris) or another reference management program..
        /// </summary>
        internal static string SendReferenceByEMailBodyText_WithAttachments {
            get {
                return ResourceManager.GetString("SendReferenceByEMailBodyText_WithAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [No short title!].
        /// </summary>
        internal static string ShortTitleMissing {
            get {
                return ResourceManager.GetString("ShortTitleMissing", resourceCulture);
            }
        }
    }
}
