//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Addons.SendReferenceByEmail.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SendReferenceByEmailResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SendReferenceByEmailResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Addons.SendReferenceByEmail.Properties.SendReferenceByEmailResource" +
                            "s", typeof(SendReferenceByEmailResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addon {
            get {
                object obj = ResourceManager.GetObject("addon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send reference by email ähnelt.
        /// </summary>
        internal static string ButtonCaption {
            get {
                return ResourceManager.GetString("ButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [en]Die Verbindung zu Outlook ist fehlgeschlagen.
        ///
        ///Bitte prüfen Sie ob Citavi und Outlook mit den gleichen Rechten ausgeführt wird. ähnelt.
        /// </summary>
        internal static string OutlookRightsMessage {
            get {
                return ResourceManager.GetString("OutlookRightsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die References from Citavi project &quot;{0}&quot;:
        ///{1}
        ///
        ///Hint:
        ///The RIS file attached contains the bibliographic information for the reference above. You can import this file into Citavi (see www.citavi.com/ris) or another reference management program. ähnelt.
        /// </summary>
        internal static string SendReferenceByEMailBodyText {
            get {
                return ResourceManager.GetString("SendReferenceByEMailBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die References from Citavi project &quot;{0}&quot;:
        ///{1}
        ///
        ///Attachments:
        ///{2}
        ///
        ///Hint:
        ///The RIS file attached contains the bibliographic information for the reference above. You can import this file into Citavi (see www.citavi.com/ris) or another reference management program. ähnelt.
        /// </summary>
        internal static string SendReferenceByEMailBodyText_WithAttachments {
            get {
                return ResourceManager.GetString("SendReferenceByEMailBodyText_WithAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [No short title!] ähnelt.
        /// </summary>
        internal static string ShortTitleMissing {
            get {
                return ResourceManager.GetString("ShortTitleMissing", resourceCulture);
            }
        }
    }
}
