//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Addons.ImportJournals.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImportJournalsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImportJournalsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Addons.ImportJournals.Properties.ImportJournalsResources", typeof(ImportJournalsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addon {
            get {
                object obj = ResourceManager.GetObject("addon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file contains invalid characters and cannot be imported..
        /// </summary>
        internal static string FileMacroNotSupportedCharactersMessage {
            get {
                return ResourceManager.GetString("FileMacroNotSupportedCharactersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text files (*.txt)|*.txt|All files (*.*)|*.*.
        /// </summary>
        internal static string FileMacroOpenFileDialogFilters {
            get {
                return ResourceManager.GetString("FileMacroOpenFileDialogFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the journal file for import (.txt format).
        /// </summary>
        internal static string FileMacroOpenFileDialogSubject {
            get {
                return ResourceManager.GetString("FileMacroOpenFileDialogSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} journals were imported.
        ///(duplicates were not imported.).
        /// </summary>
        internal static string FileMacroResultMessage {
            get {
                return ResourceManager.GetString("FileMacroResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import file….
        /// </summary>
        internal static string ImportJournalsByFileCommandText {
            get {
                return ResourceManager.GetString("ImportJournalsByFileCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From PubMed….
        /// </summary>
        internal static string ImportJournalsByPubMedCommandText {
            get {
                return ResourceManager.GetString("ImportJournalsByPubMedCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From the University of British Columbia….
        /// </summary>
        internal static string ImportJournalsByWoodwardLibraryCommandText {
            get {
                return ResourceManager.GetString("ImportJournalsByWoodwardLibraryCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import List of Journals.
        /// </summary>
        internal static string ImportJournalsMenu {
            get {
                return ResourceManager.GetString("ImportJournalsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while importing the list of journals:
        ///
        ///{0}.
        /// </summary>
        internal static string MacroImportingErrorMessage {
            get {
                return ResourceManager.GetString("MacroImportingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read file from {0}: {1}&quot;.
        /// </summary>
        internal static string PubMedMacroReadErrorMessage {
            get {
                return ResourceManager.GetString("PubMedMacroReadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} journal(s) were imported (not counting duplicates).
        /// </summary>
        internal static string PubMedMacroResultMessage {
            get {
                return ResourceManager.GetString("PubMedMacroResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} journal(s) were imported (not counting duplicates)
        ///{1} reference(s) were changed..
        /// </summary>
        internal static string WoodwardMacroResultMessage {
            get {
                return ResourceManager.GetString("WoodwardMacroResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to update journal information for references in current selection? (Journal information will be updated for all references if no selection is active)..
        /// </summary>
        internal static string WoodwardMacroUpdateMessage {
            get {
                return ResourceManager.GetString("WoodwardMacroUpdateMessage", resourceCulture);
            }
        }
    }
}
